[server]
# Enable network access
address = "0.0.0.0"
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Don't open browser automatically
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Custom theme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 